INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (21, 'Remo con barra', 'FUERZA', null, 'Agarra con ambas manos la barra y con las muñecas rectas y bloqueadas, empieza a llevarla hacia el pecho, abriendo ligeramente los codos al final.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (22, 'Martillo', 'FUERZA', null, 'Con mancuernas en cada mano, mantén los brazos extendidos a los lados. Sin mover los brazos, dobla los codos y lleva las mancuernas hacia los hombros.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (23, 'Press de banca', 'FUERZA', null, 'Recostado en el banco, los brazos estirados verticalmente, con la barra cargada en las manos, bajar la barra y luego subir hasta la posición inicial.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (15, 'Trotar', 'RESISTENCIA', null, 'Correr a un paso moderado.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (16, 'Burpees', 'CAPACIDAD AEROBICA', null, 'Se realiza en varios movimientos (nace de la unión de las flexiones de pecho, las sentadillas y los saltos verticales).');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (17, 'Correr', 'VELOCIDAD', null, 'Correr a velocidad máxima.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (18, 'Lanzamiento de balón medicinal', 'POTENCIA', null, 'Lanzar la pelota con los pies juntos flexionando rodillas intentando que llegue lo más lejos posible.');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (19, 'Plancha lateral', 'ESTABILIDAD', null, 'Nos recostamos con el costado derecho con las piernas estiradas y los pies encimados.Levantamos las caderas y apoyamos el pecho en el codo y pie derec');
INSERT INTO mydb.ejercicio (idEjercicio, nombre, tipo, video, descripcion) VALUES (20, 'Low Lunge', 'MOVILIDAD', null, 'Apoyar los pies y las manos en el suelo y extiende el pie derecho hacia atrás mientras doblas la rodilla izquierda en 90°.');
