USE taw12;

INSERT INTO ejercicio (nombre, descripcion, tipo) VALUES 
('Sentadilla', 'Ejercicio básico de fuerza para las piernas', 'FUERZA'),
('Press de banca', 'Ejercicio de fuerza para el pecho', 'FUERZA'),
('Carrera continua', 'Ejercicio de resistencia cardiovascular', 'RESISTENCIA'),
('Natación', 'Ejercicio de resistencia en el agua', 'RESISTENCIA'),
('Ciclismo', 'Actividad aeróbica que mejora la capacidad cardiovascular', 'CAPACIDAD AEROBICA'),
('Salto de cuerda', 'Ejercicio aeróbico para mejorar la coordinación y resistencia', 'CAPACIDAD AEROBICA'),
('Sprints', 'Carreras cortas a máxima velocidad', 'VELOCIDAD'),
('Correr 100m', 'Carrera de velocidad pura en distancia corta', 'VELOCIDAD'),
('Levantamiento de pesas', 'Ejercicio de alta intensidad para aumentar la potencia muscular', 'POTENCIA'),
('Clean and Jerk', 'Levantamiento de pesas olímpico para potencia explosiva', 'POTENCIA'),
('Planchas', 'Ejercicio de estabilidad para el núcleo abdominal', 'ESTABILIDAD'),
('Superman', 'Ejercicio para mejorar la estabilidad y la fuerza de la espalda baja', 'ESTABILIDAD'),
('Estiramientos dinámicos', 'Ejercicios para mejorar la movilidad articular', 'MOVILIDAD'),
('Yoga', 'Práctica de posturas para aumentar la movilidad y flexibilidad', 'MOVILIDAD'),
('Remo', 'Ejercicio de fuerza y resistencia para la parte superior del cuerpo', 'FUERZA'),
('Dominadas', 'Ejercicio de fuerza para la espalda y los brazos', 'FUERZA'),
('Flexiones', 'Ejercicio de fuerza para el pecho y los tríceps', 'FUERZA'),
('Abdominales', 'Ejercicio para fortalecer los músculos abdominales', 'FUERZA'),
('Bicicleta estática', 'Ejercicio aeróbico para mejorar la capacidad cardiovascular', 'CAPACIDAD AEROBICA'),
('Burpees', 'Ejercicio de cuerpo completo para resistencia y potencia', 'POTENCIA'),
('Remo en máquina', 'Ejercicio de resistencia y fuerza para la parte superior del cuerpo', 'RESISTENCIA'),
('Trote suave', 'Ejercicio de resistencia cardiovascular a un ritmo moderado', 'RESISTENCIA'),
('Saltos al cajón', 'Ejercicio de potencia y velocidad para las piernas', 'POTENCIA'),
('Skipping', 'Ejercicio de velocidad y coordinación', 'VELOCIDAD'),
('Zancadas', 'Ejercicio de fuerza para las piernas y glúteos', 'FUERZA'),
('Peso muerto', 'Ejercicio de fuerza para la espalda y piernas', 'FUERZA'),
('Circuito de alta intensidad', 'Entrenamiento para mejorar la resistencia y fuerza', 'RESISTENCIA'),
('Flexibilidad de piernas', 'Ejercicio para mejorar la flexibilidad de las piernas', 'MOVILIDAD'),
('Tai Chi', 'Práctica de movimientos lentos para mejorar la movilidad y equilibrio', 'MOVILIDAD'),
('Estocadas', 'Ejercicio para fortalecer las piernas y glúteos', 'FUERZA'),
('Nado mariposa', 'Estilo de natación para mejorar la fuerza y resistencia', 'RESISTENCIA'),
('Carrera de 5km', 'Carrera de distancia moderada para resistencia', 'RESISTENCIA'),
('Sprint en bicicleta', 'Ejercicio de velocidad y potencia en bicicleta', 'VELOCIDAD'),
('Carrera de obstáculos', 'Ejercicio de resistencia y agilidad', 'RESISTENCIA');

