-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 13:05:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taw12
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taw12
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taw12` DEFAULT CHARACTER SET utf8 ;
USE `taw12` ;

-- -----------------------------------------------------
-- Table `taw12`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Trabajador` (
  `idTrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  `tipo` ENUM('ENTRENADOR FUERZA', 'ENTRENADOR CROSSTRAINNING', 'DIETISTA') NOT NULL,
  `imagenPerfil` BLOB NULL,
  PRIMARY KEY (`idTrabajador`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Rutina` (
  `idRutina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idRutina`, `idTrabajador`),
  INDEX `fk_Rutina_Trabajador_idx` (`idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_Rutina_Trabajador`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `taw12`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Dieta` (
  `idDieta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idDieta`, `idTrabajador`),
  INDEX `fk_Dieta_Trabajador1_idx` (`idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_Dieta_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `taw12`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  `imagenPerfil` BLOB NULL,
  `peso` DOUBLE NULL,
  `altura` DOUBLE NULL,
  `alergias` VARCHAR(150) NULL,
  `idRutina` INT NULL,
  `idEntrenador` INT NULL,
  `idDieta` INT NULL,
  `idDietista` INT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Cliente_Rutina1_idx` (`idRutina` ASC, `idEntrenador` ASC) VISIBLE,
  INDEX `fk_Cliente_Dieta1_idx` (`idDieta` ASC, `idDietista` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Rutina1`
    FOREIGN KEY (`idRutina` , `idEntrenador`)
    REFERENCES `taw12`.`Rutina` (`idRutina` , `idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Dieta1`
    FOREIGN KEY (`idDieta` , `idDietista`)
    REFERENCES `taw12`.`Dieta` (`idDieta` , `idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` ENUM('FUERZA', 'RESISTENCIA', 'CAPACIDAD AEROBICA', 'VELOCIDAD', 'POTENCIA', 'ESTABILIDAD', 'MOVILIDAD') NOT NULL,
  `video` BLOB NULL,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idEjercicio`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`EjercicioRutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`EjercicioRutina` (
  `idEjercicioRutina` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO') NOT NULL,
  `peso` DOUBLE NULL,
  `repeticiones` VARCHAR(45) NULL,
  `series` INT NULL,
  `orden` INT NULL,
  `idRutina` INT NOT NULL,
  `idTrabajador` INT NOT NULL,
  `idEjercicio` INT NOT NULL,
  PRIMARY KEY (`idEjercicioRutina`, `idRutina`, `idTrabajador`, `idEjercicio`),
  INDEX `fk_EjercicioRutina_Rutina1_idx` (`idRutina` ASC, `idTrabajador` ASC) VISIBLE,
  INDEX `fk_EjercicioRutina_Ejercicio1_idx` (`idEjercicio` ASC) VISIBLE,
  CONSTRAINT `fk_EjercicioRutina_Rutina1`
    FOREIGN KEY (`idRutina` , `idTrabajador`)
    REFERENCES `taw12`.`Rutina` (`idRutina` , `idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EjercicioRutina_Ejercicio1`
    FOREIGN KEY (`idEjercicio`)
    REFERENCES `taw12`.`Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`SeguimientoRutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`SeguimientoRutina` (
  `fecha` DATE NOT NULL,
  `hecho` TINYINT NOT NULL,
  `peso` DOUBLE NULL,
  `repeticiones` VARCHAR(45) NULL,
  `series` INT NULL,
  `idTrabajador` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idEjercicioRutina` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`, `idCliente`, `idEjercicioRutina`),
  INDEX `fk_SeguimientoRutina_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_SeguimientoRutina_EjercicioRutina1_idx` (`idEjercicioRutina` ASC) VISIBLE,
  CONSTRAINT `fk_SeguimientoRutina_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `taw12`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeguimientoRutina_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `taw12`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeguimientoRutina_EjercicioRutina1`
    FOREIGN KEY (`idEjercicioRutina`)
    REFERENCES `taw12`.`EjercicioRutina` (`idEjercicioRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Plato` (
  `idPlato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `alergenos` VARCHAR(150) NULL,
  `video` BLOB NULL,
  `descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idPlato`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`PlatoDieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`PlatoDieta` (
  `idPlatoDieta` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO') NOT NULL,
  `calorias` INT NULL,
  `cantidad` INT NULL,
  `orden` INT NULL,
  `idPlato` INT NOT NULL,
  `idDieta` INT NOT NULL,
  `idTrabajador` INT NOT NULL,
  PRIMARY KEY (`idPlatoDieta`, `idPlato`, `idDieta`, `idTrabajador`),
  INDEX `fk_PlatoDieta_Plato1_idx` (`idPlato` ASC) VISIBLE,
  INDEX `fk_PlatoDieta_Dieta1_idx` (`idDieta` ASC, `idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_PlatoDieta_Plato1`
    FOREIGN KEY (`idPlato`)
    REFERENCES `taw12`.`Plato` (`idPlato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlatoDieta_Dieta1`
    FOREIGN KEY (`idDieta` , `idTrabajador`)
    REFERENCES `taw12`.`Dieta` (`idDieta` , `idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`SeguimientoDieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`SeguimientoDieta` (
  `fecha` DATE NOT NULL,
  `mensaje` VARCHAR(250) NULL,
  `comido` TINYINT NULL,
  `cantidad` INT NULL,
  `idTrabajador` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idPlatoDieta` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`, `idCliente`, `idPlatoDieta`),
  INDEX `fk_SeguimientoDieta_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_SeguimientoDieta_PlatoDieta1_idx` (`idPlatoDieta` ASC) VISIBLE,
  CONSTRAINT `fk_SeguimientoDieta_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `taw12`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeguimientoDieta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `taw12`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeguimientoDieta_PlatoDieta1`
    FOREIGN KEY (`idPlatoDieta`)
    REFERENCES `taw12`.`PlatoDieta` (`idPlatoDieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taw12`.`Cliente_Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw12`.`Cliente_Trabajador` (
  `idCliente` INT NOT NULL,
  `idTrabajador` INT NOT NULL,
  INDEX `fk_Cliente_has_Trabajador_Trabajador1_idx` (`idTrabajador` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Trabajador_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Trabajador_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `taw12`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Trabajador_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `taw12`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
